# Global ####

library(shiny)
library(shinydashboard)
library(tidyverse)
library(tidyquant)
library(timetk)
library(corrplot)
library(alphavantager)
library(ggplot2)
library(plotly)
library(quantmod)
library(ggplot2)
library(forecast)
library(tseries)
library(DT)
library(ggplot2)
library(prophet)
library(shinyWidgets)
library(lubridate)
library(shinycssloaders)
library(plotly)